### ISSUE TITLE
👏 

### ISSUE THREAD

**Issue by spencermountain** [gamburg/margin#14]
Just wanted to say that I find this project really novel and inspiring.
If you need any help, I'm happy to join in. I've done a considerable amount of work in markup+parsing.
Thank you for making it.

**Comment by gamburg** [comment]
Thanks @spencermountain! 

The thing we could use most right now is work on the [JavaScript parser](https://github.com/gamburg/margin/tree/master/parser/js), which I sort of hacked together – and which depends on a secondary tree library, which I think isn't ideal. I'd love for the JavaScript parser to exist as a single package that someone can download and easily try out / integrate into their own site. But I have no experience with this kind of coding. 

Similarly, creating a test suite (#4) for parsers would be very useful for encouraging people to build their own parsers (and to surface what I'm sure are numerous bugs in the current JavaScript parser).

If you ever find yourself with a few hours to spare, these are the areas I could use most help with. Though, of course, help is appreciated in whatever area of the project you find most appealing!

Thanks for your interest!
