### ISSUE TITLE
Be more specific about which characters are ignored

### ISSUE THREAD

**Issue by gamburg** [gamburg/margin#7]
Include UTF-8 values. And make sure to specify all types of possible whitespace characters. 

Originally raised by @vlmutolo

**Comment by gamburg** [comment]
And add `+` as an ignored character

**Comment by vlmutolo** [comment]
I think leaving white space as spaces (U+0020) and tabs (U+0009) would work well for most use cases. You could even just pick your favorite and make it the official `margin` white space character. That would definitely simplify parsing.

You also should consider whether or not `-` and other "ignored" characters count as whitespace in the context of indentation. Though that should probably be a separate issue.

**Comment by gamburg** [comment]
Added file: 6d0375854f96921444f7e5bfbe49f98d0bdc3f2f
Added link to spec: 41a71ba57d4115e771f1c8290f9a50cfbb14d1b9
